# Generated by Django 4.2.1 on 2023-05-08 21:49

import BookApp.models
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readbooks',
            options={'ordering': ['-date_of_reading'], 'verbose_name': 'Прочитанная книга', 'verbose_name_plural': 'Прочитанные книги'},
        ),
        migrations.AlterModelOptions(
            name='unreadbooks',
            options={'ordering': ['title'], 'verbose_name': 'Непрочитанная книга', 'verbose_name_plural': 'Непрочитанные книги'},
        ),
        migrations.AlterField(
            model_name='readbooks',
            name='estimation',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Оценка (от 0 до 10)'),
        ),
        migrations.AlterField(
            model_name='readbooks',
            name='user',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='readbooks',
            name='year_of_reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookApp.year', verbose_name='Год прочтения'),
        ),
        migrations.AlterField(
            model_name='unreadbooks',
            name='user',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
