# Generated by Django 4.2.1 on 2023-05-10 12:06

import BookApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_alter_readbooks_options_alter_unreadbooks_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='readbooks',
            name='year_of_reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookApp.year', verbose_name='Год прочтения'),
        ),
    ]
