# Generated by Django 4.2.1 on 2023-05-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0003_category_photo_alter_readbooks_year_of_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readbooks',
            name='year_of_reading',
        ),
    ]
