# Generated by Django 4.2.1 on 2023-05-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0005_readbooks_slug_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readbooks',
            name='slug_author',
        ),
    ]
