# Generated by Django 4.2.1 on 2023-05-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0010_alter_unreadbooks_author'),
    ]

    operations = [
        migrations.RenameField('Author', 'title', 'name'),
    ]
