# Generated by Django 4.2.1 on 2023-05-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0011_auto_20230514_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readbooks',
            options={'ordering': ['-date_of_reading', '-estimation'], 'verbose_name': 'Прочитанная книга', 'verbose_name_plural': 'Прочитанные книги'},
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
