# Generated by Django 4.2.1 on 2023-05-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0016_alter_readbooks_user_alter_unreadbooks_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='readbooks',
            name='categories',
            field=models.ManyToManyField(related_name='категории', to='BookApp.category'),
        ),
    ]
